version: '3.3'

services:
  sortify-be:
    container_name: sortify-be
    image: brandonrafaellovelyno/sortify-be:v1
    ports:
      - '5000:5000'
    networks:
      - sortify-network

  sortify:
    container_name: sortify
    image: brandonrafaellovelyno/sortify:v1
    ports:
      - '3000:3000'
    networks:
      - sortify-network

  sortify-model:
    container_name: sortify-model
    image: mbudis23/wca-bc:latest
    ports:
      - '8000:8000'
    networks:
      - sortify-network

networks:
  sortify-network:
    driver: bridge
