version: '3.3'

services:
  sortify-be:
    build: .
    container_name: sortify-be
    image: brandonrafaellovelyno/sortify_backend:v1
    ports:
      - '5000:5000'
    env_file:
      - .env
    networks:
      - sortify-network

networks:
  sortify-network:
    driver: bridge
