version: '3.3'

services:
  sortify-be:
    container_name: sortify-be
    image: brandonrafaellovelyno/sortify_backend:v3.1
    ports:
      - '5000:5000'
    env_file:
      - .env
    networks:
      - sortify-network

  sortify-fe:
    container_name: sortify-fe
    image: brandonrafaellovelyno/sortify_frontend:v3
    ports:
      - '3000:3000'

  sortify-model:
    container_name: sortify-model
    image: mbudis23/wca-bc:latest
    ports:
      - '8000:8001'
    networks:
      - sortify-network

networks:
  sortify-network:
    driver: bridge
