version: '3.8'

services:
  sortify-be:
    container_name: sortify-be
    image: brandonrafaellovelyno/sortify-be:latest
    ports:
      - '5000:5000'
    networks:
      - sortify-network

  sortify:
    container_name: sortify
    image: brandonrafaellovelyno/sortify:latest
    ports:
      - '3000:3000'
    networks:
      - sortify-network

networks:
  sortify-network:
    name: sortify-network
    driver: bridge
